all: q3_1 q3_2a q3_2b q3_2c q3_3a q3_3b q3_3c

q3_1:
	g++ -O3 -Wall q3_1.cpp -o q3_1.o
	time ./q3_1.o 1
	time ./q3_1.o 5
	time ./q3_1.o 10
	time ./q3_1.o 100
	echo "\n"

q3_2a:
	nvcc q3_2a.cu -o q3_2a.o
	nvprof ./q3_2a.o 1
	nvprof ./q3_2a.o 5
	nvprof ./q3_2a.o 10
	nvprof ./q3_2a.o 100
	echo "\n"

q3_2b:
	nvcc q3_2b.cu -o q3_2b.o
	nvprof ./q3_2b.o 1
	nvprof ./q3_2b.o 5
	nvprof ./q3_2b.o 10
	nvprof ./q3_2b.o 100
	echo "\n"

q3_2c:
	nvcc q3_2c.cu -o q3_2c.o
	nvprof ./q3_2c.o 1
	nvprof ./q3_2c.o 5
	nvprof ./q3_2c.o 10
	nvprof ./q3_2c.o 100
	echo "\n"

q3_3a:
	nvcc q3_3a.cu -o q3_3a.o
	nvprof ./q3_3a.o 1
	nvprof ./q3_3a.o 5
	nvprof ./q3_3a.o 10
	nvprof ./q3_3a.o 100
	echo "\n"

q3_3b:
	nvcc q3_3b.cu -o q3_3b.o
	nvprof ./q3_3b.o 1
	nvprof ./q3_3b.o 5
	nvprof ./q3_3b.o 10
	nvprof ./q3_3b.o 100
	echo "\n"

q3_3c:
	nvcc q3_3c.cu -o q3_3c.o
	nvprof ./q3_3c.o 1
	nvprof ./q3_3c.o 5
	nvprof ./q3_3c.o 10
	nvprof ./q3_3c.o 100
	echo "\n"
